import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto', weight: "100" })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={`${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
